name: panda
channels:
  - dglteam
  - defaults
  - conda-forge
dependencies:
  - dgl-cuda11.3=0.8.2
  - python=3.7.13
  - scipy=1.7.3
  - setuptools=61.2.0
  - pip:
      - networkit==10.1
      - networkx==2.6.3
      - numba==0.55.1
      - numpy==1.21.6
      - ogb==1.3.3
      - pandas==1.3.5
      - pillow==9.1.0
      - pip==23.3.2
      - pyyaml==6.0
      - scikit-learn==1.0.2
      - torch==1.11.0+cu113
      - torch-cluster==1.6.0
      - torch-geometric==2.0.4
      - torch-scatter==2.0.9
      - torch-sparse==0.6.13
      - torch-spline-conv==1.2.1
      - torchaudio==0.11.0+cu113
      - torchvision==0.12.0+cu113
      - tqdm==4.64.0
      - wandb==0.16.1